name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Configure and build
      run: |
        mkdir build
        cd build
        cmake ..
        make
        # You may need additional steps depending on your project setup
        
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
